### ISSUE TITLE
Support for this.constructor.html

### ISSUE THREAD

**Issue by sergiucaraian** [mydesireiscoma/es6-string-html#11]
Hello,

I'm having an use case in which I have a tagged template literal function statically defined on multiple classes. This means that I have to use it like this:
``const generatedHTML = this.constructor.html`<div>content</div>` ``

I've seen that the extension already applies syntax highlighting if the tagged template function is html, but it doesn't for this.constructor.html. I think that the best solution would be to apply syntax highlighting if the template string is preceded by .html or html.

Otherwise the library is great and it's more powerful in practice than the alternatives. Thank you for developing it.

**Comment by mydesireiscoma** [comment]
Thanks a lot for the suggestion. 
I'll implement this feature as soon as possible

**Comment by mydesireiscoma** [comment]
I tried to add support for all cases
I mean, both cases should work now
```js 
const myFavoriteConst = this.constructor.html`<div>For my favorite tag</div>
```
```js 
const myFavoriteConst = myFavoriteClass.html`<div>For my favorite dog</div>
```
```js 
const myFavoriteConst = html`<div>And my favorite tag</div>
```
...and so on.

Package in the marketplace is updated. Check, if it works as you expected.
Feel free to make any suggestions

Happy to help you

**Comment by sergiucaraian** [comment]
It works great. Thanks a lot for the help!

I have one other suggestion, but i'll put it in a separate thread.
