### ISSUE TITLE
Line comment without following string literal breaks syntax hightlighting

### ISSUE THREAD

**Issue by SirAiedail** [mydesireiscoma/es6-string-html#13]
A line comment that starts with `html` but is not followed by a temlate literal breaks syntax highlighting for the rest of the file.

Minimal example:
```js
const foo = 'html'; // html is awesome
console.log(foo);
```

The part before the comment is displayed correctly, but the comment and the next line are default text color and VS code showes JS completion when typing inside the comment.

**Comment by mydesireiscoma** [comment]
Will be fixed in next 24 hours. 
Thankyou

**Comment by SirAiedail** [comment]
Issue is fixed
