### ISSUE TITLE
Wrapped Multi-line support appears to have broken

### ISSUE THREAD

**Issue by brblord** [mydesireiscoma/es6-string-html#15]
We'll often use this in a jQuery wrapper like so:

```js
$( //html
`<div>
     <div>Test</div>
 </div>
`);
```

Previously this has worked great.  However, in the latest update the above format doesn't work.  It does still work fine if it is not wrapped in parentheses like so: 

```js
const content = //html
`<div>
     <div>Test</div>
 </div>`;
```

I have noticed that if I put the opening back-tick on the same line as the html comment, it will work in the jQuery wrapper:

```js
$( //html`
<div>
  <div>Test</div>
</div>` );
```

**Comment by mydesireiscoma** [comment]
@brblord
 
Fixed
Package in the marketplace is updated
Feel free to close the issue if the plugin works as you expected

Thankyou
