### ISSUE TITLE
Question: Using this repo as a starting place for an equivalent feature for Python

### ISSUE THREAD

**Issue by ptweir** [mydesireiscoma/es6-string-html#16]
Hi, Thank you for what looks like a great plugin! I'm looking for a way to add SQL- or HTML-highlighting to strings in Python scripts (.py files) and I'm wondering if branching off your work would be a good way to start. Any tips would be appreciated!

**Comment by mydesireiscoma** [comment]
Hi, Thank you!
Sure. Feel free to make a fork for your needs.
If you will need any help - just let me know.
Here are some links what can be useful for you.
> My bad. I have to add the project documentation.

Visual Studio Code uses `tmLanguage` for syntax highlighting.  
- [tmLanguage tutorial](https://www.apeth.com/nonblog/stories/textmatebundle.html)
- [Official tmLanguage docs](https://macromates.com/manual/en/language_grammars)
- [Official VSCode syntax highlighting docs](https://code.visualstudio.com/docs/extensionAPI/language-support#_syntax-highlighting)
- [VSCode language identifiers list](https://code.visualstudio.com/docs/languages/identifiers)
