### ISSUE TITLE
add html text as parameter argument support

### ISSUE THREAD

**Issue by EdSaleh** [mydesireiscoma/es6-string-html#17]
Hello,

Currently, the extension supports string html only scope level but not at parameter level. 
e.g. 

    function foo(){   }
    foo(//html
        `<div>
        <p>
        </p>
        </div>`)

will not work.

Thank You,

**Comment by mydesireiscoma** [comment]
Hi
Thanks a lot for using my plugin
I'll try to fix it

**Comment by EdSaleh** [comment]
It works only when the html is the first parameter and the comment placed right next the argument bracket.

    //works
    hello(//html
    `<div></div>`)

    //doesn't works
    hello(a, //html
        `<div></div>`)

    //doesn't works
    hello(
    //html
    `<div></div>`)

Thank you for this great plugin and work!

**Comment by mydesireiscoma** [comment]
@laurieryayoi
Fixed. 
Except last case 
```js
//html
`<div></div>`
```
Seems like, there is VSCode limitatios about regular expressions for syntax highlighting.
If I'll find a way to fix it, I'll let you know.

Package in the marketplace is updated. (1.8.6)
Feel free to close issue, if plugin works as you expected

**Comment by mydesireiscoma** [comment]
@EdSaleh 
Fixed. 
Except last case 
```js
//html
`<div></div>`
```
Seems like, there is VSCode limitatios about regular expressions for syntax highlighting.
If I'll find a way to fix it, I'll let you know.

Package in the marketplace is updated. (1.8.6)
Feel free to close issue, if plugin works as you expected
