### ISSUE TITLE
Plugin doesn't work in html files

### ISSUE THREAD

**Issue by laurieryayoi** [mydesireiscoma/es6-string-html#18]
![img](https://puu.sh/CC8u2/d2445b70a6.png)
When i write templates i must change  language mode to javascript with wrong highlight thousands of errors....
Can it work in html script tags?

**Comment by mydesireiscoma** [comment]
Hi
I guess, its possible
I'll try to fix

**Comment by mydesireiscoma** [comment]
@laurieryayoi 
Fixed. Package in the marketplace is updated. (1.8.6)
Feel free to close issue, if plugin works as you expected

**Comment by laurieryayoi** [comment]
> @laurieryayoi
> Fixed. Package in the marketplace is updated. (1.8.6)
> Feel free to close issue, if plugin works as you expected

It's awesome, thanks a lot!
