### ISSUE TITLE
Doesn't work when passed directly into a function

### ISSUE THREAD

**Issue by speigg** [mydesireiscoma/es6-string-html#19]
When passing into a function directly, the syntax highlighting and IntelliSense doesn't activate. 

ex:

```ts 
render(html`
   <div>
      ...
   </div>
`)
```

**Comment by mydesireiscoma** [comment]
@speigg 
Fixed. Package in the marketplace is updated. (1.8.6)
Feel free to close issue, if plugin works as you expected
