### ISSUE TITLE
shortkey

### ISSUE THREAD

**Issue by djmisterjon** [mydesireiscoma/es6-string-html#2]
If you like the idea, it can be cool to add a quick shortkey.
maybe something like.
**CTRL+ALT+H**

Thank you plugin work very well.

**Comment by mydesireiscoma** [comment]
I'm sorry, can you describe what actually it will do, please?

**Comment by djmisterjon** [comment]
@mydesireiscoma  a shortcut for auto write 
_/*html*/_
yes, I am an extreme laziness. :)

**Comment by mydesireiscoma** [comment]
@djmisterjon 
I'll take a look what I can do

**Comment by mydesireiscoma** [comment]
Closed by commit d92a6ba
Extension is updated
