### ISSUE TITLE
Syntax coloring breaks after template or html word in tsx files

### ISSUE THREAD

**Issue by dimitardishev** [mydesireiscoma/es6-string-html#20]
I'm using the template word a lot around my project as you can see on the screenshot.
The coloring of the code after the keyword looks like a raw text
Currently I observe this only in .tsx files

VS Code info
Version: 1.31.1
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:19:29.629Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.18.0-15-generic

es-string-html version: 1.8.6

![selection_090](https://user-images.githubusercontent.com/37380766/52697407-12d56000-2f7a-11e9-9be7-51c8b4097898.jpg)

**Comment by mydesireiscoma** [comment]
Thanks for the report
Will be fixed soon

**Comment by mydesireiscoma** [comment]
@dimitardishev 
Fixed. Package in the marketplace is updated. (1.8.7)
Feel free to close issue, if plugin works as you expected
