### ISSUE TITLE
css intellisense

### ISSUE THREAD

**Issue by coltpini** [mydesireiscoma/es6-string-html#25]
when a style tag is in the HTML the css doesn't get intellisense. This is a key feature for custom elements.

VS code - Version 1.34.0 (1.34.0)
component version - 1.8.8

**Comment by coltpini** [comment]
I am happy to submit a PR, I am just not familiar with the development process for VSCode. I am looking through some of the documentation.

**Comment by mydesireiscoma** [comment]
Hi
I'm sorry, but it's currently impossible at the current moment
It's just syntax highlighting plugin. For code folding and autocomplete features this plugin should be implemented as a custom language plugin.
