### ISSUE TITLE
Code folding possible?

### ISSUE THREAD

**Issue by leosdad** [mydesireiscoma/es6-string-html#26]
Hi, this extension is exactly what I was looking for! I wonnder if it would be possible to allow code folding inside es6 multiline strings... Thanks!

**Comment by mydesireiscoma** [comment]
Hi
I'm sorry, but it's currently impossible at the current moment
It's just syntax highlight. For code folding and autocomplete features this plugin should be implemented as a custom language plugin.

**Comment by leosdad** [comment]
I already suspected that, thanks for answering.

**Comment by rangav** [comment]
Hi  i was also looking for code folding in multiline string, its possible now with VS code setting

see this link
https://stackoverflow.com/a/60006522
