### ISSUE TITLE
fake copy ?

### ISSUE THREAD

**Issue by djmisterjon** [mydesireiscoma/es6-string-html#3]
it's me or its have a fake copy of you plugin on the market ? v1.1.0 !?
https://marketplace.visualstudio.com/items?itemName=hjb2012.vscode-es6-string-html

**Comment by mydesireiscoma** [comment]
Someone did fork from `v1.0.0`, added `Prettier` support and published it on the market.
I have no idea, why he did it, without opening an issue.

So, actually, it's not a fake
