### ISSUE TITLE
js syntaxe color?  `${code()};`

### ISSUE THREAD

**Issue by djmisterjon** [mydesireiscoma/es6-string-html#6]
Hi, i just notice javascript not get syntaxe color?
It is not urgent, but it will help for the eyes.
It would be great if you could make JS syntax highlighting compatible.

![image](https://user-images.githubusercontent.com/24865815/37700268-2eb1a75a-2cc1-11e8-915b-ffe643ebedc5.png)

thank for your awesome plugin.

in the prinscreen you can look 
`${type==='spinesheets' && appendSpineData()};`

the original color should look like thats.
![image](https://user-images.githubusercontent.com/24865815/37700539-4e1eb960-2cc2-11e8-9fd9-f184eece25f5.png)

**Comment by mydesireiscoma** [comment]
Fixed
Package in the marketplace is updated
