### ISSUE TITLE
Add support to configure triggers

### ISSUE THREAD

**Issue by bashmish** [mydesireiscoma/es6-string-html#7]
Currently we can use these options before template literals to highlight it's content as html: 
1. `/*html*/`\``<html></html>`\`
2. `/*inline-html*/`\``<html></html>`\`
3. `/*template*/`\``<html></html>`\`
4. `/*inline-template*/`\``<html></html>`\`
5. html\``<html></html>`\`

This can be generalised as: highlight html if before the template literal a certain pattern/string is found. So it should be possible to add configuration option to support any arbitrary pattern before template literals to trigger highlighting.

For example in our projects we already have a convention that everything after "html: " needs highlighting. It looks like this:

```js
MyHelper.init({
  html: `
    <div>Hello, world!</div>
  `
});
``` 

Of course we can add a comment everywhere, but it seems like there is a more elegant solution to support such conventions automatically.

Also we can think of other similar cases like assignment expression to an html variable or a property with a name "html".

```js
const html = `<div>Hello, world!</div>`;
myObj.html = `<div>Hello, world!</div>`;
```

So in this case a string before a template triggering the highlighting is "html = ".

Taking all mentioned cases I see this configuration option in VSCode settings as smth like:

```json
{
  "es6StringHtml.triggerPatterns": ["html: ", "html = "]
}
```

RegExps could be also possible here.

I didn't check the current implementation of triggers and if any JS parsing and AST are involved, but even if yes, I don't see any objections to not provide such a configuration option on top of whatever is currently already working, if VSCode is flexible enough, of course. I can help with the implementation.

**Comment by mydesireiscoma** [comment]
I'll take a look what I can do

**Comment by mydesireiscoma** [comment]
I'm sorry but seems like there is no possibility to access settings from a syntax highlighting configuration file
If you will find a way how to solve this issue, feel free to contact me or make a pull request

I can add `((\.|\s|^)html\s?=\s?)` as a temporary fix if you need it urgently
Anyway, feel free to make any suggestions

**Comment by bashmish** [comment]
I took a look and also didn't find any way to make it configurable. I think this needs to be supported on VSCode platform level so that plugin could have more control. For now I would close this issue here and see if I can bring it up on VSCode project. Thanks for your help!
