### ISSUE TITLE
Syntax Highlighting in Attribute Values

### ISSUE THREAD

**Issue by andrewjmead** [mydesireiscoma/es6-string-html#8]
Thanks for the work you've put into this plugin. It's been super useful.

I noticed that syntax highlighting and autocompletion don't work with placeholders in attribute values. The example below shows this.

Example snippet:

```javascript
const data = 'Andrew'
const example = html`
    <div class="${data}">${data}</div>
`;
```
Output:

<img width="325" alt="screen shot 2018-04-10 at 11 13 46 am" src="https://user-images.githubusercontent.com/2992789/38565828-4dd6a0e6-3cb0-11e8-9d23-8376c0c92e85.png">

The placeholder for data in the attribute value isn't highlighted. The placeholder for data in the element content is highlighted.

Is there anyway I can fix this so highlighting and autocompletion can be used everywhere?

**Comment by mydesireiscoma** [comment]
I'll try to fix this issue

**Comment by mydesireiscoma** [comment]
![2018-04-12 18-44-12](https://user-images.githubusercontent.com/12423383/38666119-8d11e2ac-3e81-11e8-86d5-19f971eb89a0.png)
For some reasons, I have no such issue

Maybe you have installed some plugin, which conflicts with `es6-string-html`?
